// GENERATED by .design-sync/make-entry.mjs — do not edit by hand.
// Bundle entry for design-sync: re-exports the real shipped components.

// shadcn primitives (src/components/ui)
export * from "@/components/ui/alert-dialog";
export * from "@/components/ui/badge";
export * from "@/components/ui/button";
export * from "@/components/ui/card";
export * from "@/components/ui/collapsible";
export * from "@/components/ui/command";
export * from "@/components/ui/context-menu";
export * from "@/components/ui/dialog";
export * from "@/components/ui/dropdown-menu";
export * from "@/components/ui/input";
export * from "@/components/ui/label";
export * from "@/components/ui/scroll-area";
export * from "@/components/ui/select";
export * from "@/components/ui/separator";
export * from "@/components/ui/sheet";
export * from "@/components/ui/sonner";
export * from "@/components/ui/switch";
export * from "@/components/ui/tabs";
export * from "@/components/ui/textarea";
export * from "@/components/ui/tooltip";

// application components (src/components)
export * from "@/components/AgentColorSwatch";
export * from "@/components/AgentControls";
export * from "@/components/AgentFormFields";
export * from "@/components/AgentLayout";
export * from "@/components/AgentSubscriptions";
export * from "@/components/AliasEditor";
export * from "@/components/AttachButton";
export * from "@/components/AuditExportActions";
export * from "@/components/AuditRow";
export * from "@/components/ComboField";
export * from "@/components/CustomerQuestionNotifications";
export * from "@/components/DaemonBanner";
export * from "@/components/DaemonProvider";
export * from "@/components/DesktopUpdates";
export * from "@/components/EditablePresetCombobox";
export * from "@/components/FileBrowser";
export * from "@/components/FullAuditLog";
export * from "@/components/GoalHelp";
export * from "@/components/GroupWizard";
export * from "@/components/HostStatus";
export * from "@/components/HostSwitcher";
export * from "@/components/ImageLayout";
export * from "@/components/InboxComposer";
export * from "@/components/IterationAuditLog";
export * from "@/components/IterationJudgePanel";
export * from "@/components/IterationTimeoutControl";
export * from "@/components/LoopControls";
export * from "@/components/NotesEditor";
export * from "@/components/PathAutocomplete";
export * from "@/components/ProxyCallRow";
export * from "@/components/RetentionPanel";
export * from "@/components/SecretsPanel";
export * from "@/components/SendFilesButton";
export * from "@/components/ShellScriptEditor";
export * from "@/components/StatusChatHistory";
export * from "@/components/SupportBundle";
export * from "@/components/ThemeToggle";
export * from "@/components/TuiScreen";
export * from "@/components/theme-provider";

// page-level surfaces (src/pages)
export * from "@/pages/terminals/TerminalsPage";
export * from "@/pages/terminals/SidebarStateProvider";
export * from "@/pages/agents/AgentWorkspace";
export * from "@/pages/tasks/TasksWorkspace";
export * from "@/pages/tasks/TaskDetail";
export * from "@/pages/settings/SettingsPage";
export * from "@/pages/DaemonsPage";
export * from "@/pages/ImagesPage";
export * from "@/pages/StoresPage";

// Default exports: `export *` does not forward a module default, so any
// default-exported component has to be named explicitly or it never reaches
// the bundle (validate catches this as [BUNDLE_EXPORT]).
export { default as FileBrowser } from "@/components/FileBrowser";
export { default as TerminalsPage } from "@/pages/terminals/TerminalsPage";
export { default as AgentWorkspace } from "@/pages/agents/AgentWorkspace";
export { default as TasksWorkspace } from "@/pages/tasks/TasksWorkspace";
export { default as TaskDetail } from "@/pages/tasks/TaskDetail";
export { default as SettingsPage } from "@/pages/settings/SettingsPage";
export { default as DaemonsPage } from "@/pages/DaemonsPage";
export { default as ImagesPage } from "@/pages/ImagesPage";
export { default as StoresPage } from "@/pages/StoresPage";

// Contexts components read but that live outside src/components. A preview
// must wrap with the SAME context instance the bundled component consumes,
// so these have to travel in the bundle rather than being imported from
// source in the preview (that would create a second, unrelated context).
export { AgentNameContext, AgentStatusContext } from "@/lib/agent";
export { CustomerQuestionNotificationsContext } from "@/components/customerQuestionNotificationsContext";

// Router context for previews of components that use react-router links.
// Excluded from the component list via cfg.componentSrcMap.
// MemoryRouter alone matches no pattern: AgentLayout and ImageLayout read
// useParams(), so a preview must mount them inside a matched Route.
export { MemoryRouter, Routes, Route } from "react-router-dom";

// sonner's imperative API. Toaster subscribes to the toast singleton in THIS
// bundle; a preview importing "sonner" directly would get a second copy and
// its toasts would never reach the mounted Toaster. Lowercase, so the
// converter never treats it as a component.
export { toast } from "sonner";
