// Emits .design-sync/entry.tsx — the design-sync bundle entry. Tariboy UI is an
// app, not a published library: there is no dist and no .d.ts tree, so the
// bundle entry is generated here by re-exporting the real component modules
// (never reimplementing them). Re-run after adding or removing a component file.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const ui = readdirSync(join(here, '../src/components/ui'))
  .filter((f) => f.endsWith('.tsx') && !f.endsWith('.test.tsx'))
  .sort();
const applied = readdirSync(join(here, '../src/components'))
  .filter((f) => f.endsWith('.tsx') && !f.endsWith('.test.tsx'))
  .sort();

// Page-level surfaces: the real screens the app routes to — whole compositions
// rather than atoms — so the design agent sees Tariboy's actual density and
// layout. Deliberately an explicit SHORT list, not a walk of src/pages: every
// module here lands in the shipped bundle, and re-exporting all 63 pages pushed
// it to 5.6 MB, where the render check's first (cold-start) card began losing
// its race against bundle parse. These seven plus their own imports are what the
// page cards need. Verified to have no export-name collisions with
// src/components.
const pages = [
  'terminals/TerminalsPage.tsx',
  // Not a screen: the shared sidebar-state provider TerminalsPage reads. It has
  // to travel in the bundle so a preview wraps the SAME provider instance.
  'terminals/SidebarStateProvider.tsx',
  'agents/AgentWorkspace.tsx',
  'tasks/TasksWorkspace.tsx',
  'tasks/TaskDetail.tsx',
  'settings/SettingsPage.tsx',
  // The /hosts section body SettingsPage routes to. Without it the SettingsPage
  // preview's Hosts cell renders `undefined` ("Element type is invalid") - the
  // shell draws, the right-hand pane stays blank.
  'DaemonsPage.tsx',
  'ImagesPage.tsx',
  'StoresPage.tsx',
];

const lines = [
  '// GENERATED by .design-sync/make-entry.mjs — do not edit by hand.',
  '// Bundle entry for design-sync: re-exports the real shipped components.',
  '',
  '// shadcn primitives (src/components/ui)',
  ...ui.map((f) => `export * from "@/components/ui/${f.replace(/\.tsx$/, '')}";`),
  '',
  '// application components (src/components)',
  ...applied.map((f) => `export * from "@/components/${f.replace(/\.tsx$/, '')}";`),
  '',
  '// page-level surfaces (src/pages)',
  ...pages.map((f) => `export * from "@/pages/${f.replace(/\.tsx$/, '')}";`),
  '',
  '// Default exports: `export *` does not forward a module default, so any',
  '// default-exported component has to be named explicitly or it never reaches',
  '// the bundle (validate catches this as [BUNDLE_EXPORT]).',
  ...applied
    .filter((f) =>
      /^export default/m.test(
        readFileSync(join(here, '../src/components', f), 'utf8'),
      ),
    )
    .map((f) => {
      const stem = f.replace(/\.tsx$/, '');
      return `export { default as ${stem} } from "@/components/${stem}";`;
    }),
  ...pages
    .map((f) => [f, readFileSync(join(here, '../src/pages', f), 'utf8')])
    .map(([f, src]) => [f, /^export default function (\w+)|^export default (\w+)/m.exec(src)])
    .filter(([, m]) => m)
    .map(([f, m]) => {
      const name = m[1] ?? m[2];
      return `export { default as ${name} } from "@/pages/${f.replace(/\.tsx$/, '')}";`;
    }),
  '',
  '// Contexts components read but that live outside src/components. A preview',
  '// must wrap with the SAME context instance the bundled component consumes,',
  '// so these have to travel in the bundle rather than being imported from',
  '// source in the preview (that would create a second, unrelated context).',
  'export { AgentNameContext, AgentStatusContext } from "@/lib/agent";',
  'export { CustomerQuestionNotificationsContext } from "@/components/customerQuestionNotificationsContext";',
  '',
  '// Router context for previews of components that use react-router links.',
  '// Excluded from the component list via cfg.componentSrcMap.',
  '// MemoryRouter alone matches no pattern: AgentLayout and ImageLayout read',
  '// useParams(), so a preview must mount them inside a matched Route.',
  'export { MemoryRouter, Routes, Route } from "react-router-dom";',
  '',
  '// sonner\'s imperative API. Toaster subscribes to the toast singleton in THIS',
  '// bundle; a preview importing "sonner" directly would get a second copy and',
  '// its toasts would never reach the mounted Toaster. Lowercase, so the',
  '// converter never treats it as a component.',
  'export { toast } from "sonner";',
  '',
];
writeFileSync(join(here, 'entry.tsx'), lines.join('\n'));
console.log(`entry.tsx: ${ui.length} ui + ${applied.length} app modules`);
