// Package builtinimages builds and embeds daemon-owned default images.
package builtinimages

import "embed"

// FS contains the bundle generated by make build-basic-image. A committed
// placeholder keeps direct development builds valid when generation is skipped.
//
//go:embed generated/*
var FS embed.FS
