name: Pull request checks

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    name: make check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: |
            ui/package-lock.json
            docs/package-lock.json

      - name: Install UI dependencies
        run: npm ci
        working-directory: ui

      - name: Install documentation dependencies
        run: npm ci
        working-directory: docs

      - name: Run checks
        run: make check
